* RrFramework

RrFramework abstracts platform layer and exposes easy to use graph-based graphics API implemented on top of Vulkan.
It comes with its own IMGUI style API for quick prototyping of user interfaces and creation of development tooling.

#+begin_quote
Not yet suitable for anything remotely serious.
#+end_quote

* Requirements

+ Windows/Linux/macOS
+ Modern C/C++ Compiler
  - MSVC 17.8.4+
  - GCC 13+
  - Clang 17+
+ CMake 3.28+
+ Vulkan SDK 1.1+
  - Can be configured to use Vulkan 1.0 under Windows and Linux

* Using RrFramework

You can find examples in =Examples/= folder.
These don't use some shared framework and are designed to be standalone.
Preferred build system is CMake. You can use built-in =FetchContent= or [[https://github.com/cpm-cmake/CPM.cmake][CPM.cmake]]
to make RrFramework available to your project.
Then simply link your application against it,
#+BEGIN_SRC cmake
  target_link_libraries(${PROJECT_NAME} PRIVATE RrFramework)
#+END_SRC

* Acknowledgements

+ [[https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator][VulkanMemoryAllocator]]
+ [[https://github.com/glfw/glfw][GLFW]]
+ [[https://github.com/libsdl-org/SDL][SDL]]
+ [[https://github.com/jkuhlmann/cgltf][cgltf]]
+ [[https://github.com/Cyan4973/xxHash][xxHash]]
+ [[https://github.com/nothings/stb][stb]] - TrueType and images
+ [[https://github.com/EpicGamesExt/raddebugger][RAD Debugger]] - Arena implementation
+ [[https://nullprogram.com/][Chris Wellons]] - Arena-friendly data structures

* License

[[LICENSE.org][MIT]]
