* Critical

- [X] Synchronization (?) bug with host written buffers.
      Turned out to be an issue of writing to host visible buffers before waiting on the fence associated with current frame.
      Solution: call Iterate() after waiting on the fence.
- [X] Add deletion queues for Vulkan objects.
- [X] Things such as rendering to cubemap requires more advanced image view handling.
      A hive of wrapped image views + hash?
      Solution: implemented custom storage for views that combines a hive and a map.
      Any image view gets created on demand unless it's already cached in storage.
- [X] Hash collision handling across all usages of Rr_Map.
- [X] Hashing objects such as VkFramebuffer looks very bad.
- [X] Simplify pipeline layout creation.
- [ ] Inter-node sync, e.g., sequential compute dispatches writing to the same resource.
- [ ] Remove Rr_LoadingThread.
      Current plan is to decouple Rr_Graph from Rr_Frame and make it possible to create subgraphs (possibly from other threads).
      For now, make transfer-only graphs that can be submitted from secondary threads.
- [ ] Should referenced pipelines and samplers be hashed to optimize decrement references pass? 
- [ ] Binding arrays support.
- [ ] 3D image support.
- [ ] Image array support.
- [ ] MSAA support.
- [ ] Check if descriptor set layouts are properly hashed.

* Features

** User Interface

- [X] Combobox.
- [X] Auto-resizing windows.
- [X] Sliders.
- [ ] Sane size defaults for resizable windows.
- [ ] Support for linear color space swapchains.
      Put colors into an array for easier conversion. 
- [ ] Horizontal scrollbar.
- [ ] Keyboard input and related widgets.
- [ ] Color picker.
- [ ] Radio buttons.
- [ ] Nested windows.
- [ ] Swap font rendering with stb_truetype.

** Debug Overlay

- [ ] Very basic profilers for CPU/GPU.
- [ ] Memory arena registry and maybe some kind of memory profiler.

** GLTF

- [ ] Add support for skeletal animation.
- [ ] Examine current implementation and see if it's good enough.

** Examples

- [ ] Pre-rendered depth.
- [ ] Dissolving text.
- [ ] Rendering to cubemap.
- [ ] Shadows.

** Low-priority

- [X] Move to GLFW.
- [X] Move to C11.
- [X] Remove InputMap.
- [ ] Replace VMA with custom allocator.
- [ ] Own implementation of Windows/Linux platform layers.
- [ ] Macro-based stuff should probably be internal.
      The goal is clean and minimal API that's 99% accessible from other languages.
