* Critical

- [X] Synchronization (?) bug with host written buffers.
      Turned out to be an issue of writing to host visible buffers before waiting on the fence associated with current frame.
      Solution: call Iterate() after waiting on the fence.
- [X] Add deletion queues for Vulkan objects.
- [X] Things such as rendering to cubemap requires more advanced image view handling.
      A hive of wrapped image views + hash?
      Solution: implemented custom storage for views that combines a hive and a map.
      Any image view gets created on demand unless it's already cached in storage.
- [X] Hash collision handling across all usages of Rr_Map.
- [X] Hashing objects such as VkFramebuffer looks very bad.
- [X] Simplify pipeline layout creation.
      In the end it had to be more complex though.
- [X] Inter-node sync, e.g., sequential compute dispatches writing to the same resource.
      Added RW versions of Rr_BindStorageXXX commands for better synchronization opportunities.
      Added Rr_ComputeBarrier() for compute nodes.
      Since you can't put barriers amidst render passes, it's user responsibility to avoid undefined behavior.
- [X] Remove Rr_LoadingThread.
      Remove Rr_UploadImageXXX stuff which is going to be replaced by graph nodes.
      Current plan is to decouple Rr_Graph from Rr_Frame and make it possible to create subgraphs (possibly from other threads).
      For now, make transfer-only graphs that can be submitted from secondary threads.
- [X] Finalize said decoupling:
  1) Track graph capabilities.
  2) Move arena and command pools to thread context.
- [X] Should referenced pipelines and samplers be hashed to optimize decrement references pass? 
      Solution: put handles to hash set.
- [X] Binding arrays support.
- [X] 3D image support.
- [X] Image array support.
- [X] Refactor duplicated code in Rr_ExecuteComputeNode and Rr_ExecuteGraphicsNode functions.
- [X] MSAA support.
- [X] Check if descriptor set layouts are properly hashed.
- [X] Refactor Rr_AddXXXNode functions to ensure better type safety.
- [X] See if it's possible to get rid of descriptor allocator arenas.
- [X] Make locking more granular. gRenderer->Lock should only be locked when allocating.
- [ ] Minimal error handling pass.
      Implement Rr_GetErrorString().
  1) Image/buffer creation.
  2) Graph node creation.
  3) Binding resources.
- [ ] Support for immutable buffers/images that don't require synchronization.
- [ ] Public API should use const where applicable.
- [ ] Does PushXXXIntoHive need to return iterator?
- [ ] Releasing same resource (buffer, image, etc) twice leads to annoying bugs.
- [ ] Framebuffers/SyncStates require different hash table implementation. Current implementation is a mess...

* Features

** User Interface

- [ ] Shift-Enter doesn't work.
- [ ] Enter at cursor 0 doesn't work.
- [X] Escape to close popup windows.
- [X] Allow having scroll area width larger than line height.
- [X] Separate colors for comboboxes.
- [X] Separate colors for radio buttons.
- [X] Hex color copy/paste.
- [X] Backspace in input fields.
- [X] Separate window/contens padding.
- [X] Auto resize ignores title width.
- [X] Input fields with custom clip rects happen to ignore parent bounds.
- [ ] Better tabs.
- [X] Upgrade click system to allow double clicking titles.
      Also fix input field flicker.
- [X] Add separate ID/Hash stack.
- [X] Fix broken clip rects.
- [X] Apply scalar changes immediately if possible.
- [X] Make drag behavior properly handle buttons and support double clicks.
- [X] Support for linear color space swapchains.
      Put colors into an array for easier conversion. 
- [X] Draggable scalars.
- [X] Clamps/ratios for draggable scalars.
- [ ] Some options for horizontal child layouts + asserts.
- [X] Combobox.
- [X] Auto-resizing windows.
- [X] Sliders.
- [X] Keyboard input and related widgets.
- [X] Color picker.
- [X] Radio buttons.
- [X] Nested windows.
- [X] Swap font rendering with stb_truetype.
- [ ] More animations.
- [ ] Proper stack data structure.
- [ ] Horizontal scrollbar.

** Debug

- [ ] Very basic profilers for CPU/GPU.
- [ ] Memory arena registry and maybe some kind of memory profiler.
- [X] Vulkan markers.
- [ ] Allow inserting debug markers not associated with nodes.
- [ ] Separate define for Vulkan markers.

** GLTF

- [ ] Add support for skeletal animation.
- [ ] Examine current implementation and see if it's good enough.

** Examples

- [ ] Pre-rendered depth.
- [ ] Dissolving text.
- [X] Modern rendering: shadows, rendering to cubemap, post-processing, etc.

** Low-priority

- [X] Move to GLFW.
- [X] Move to C11.
- [X] Move back to C99!
- [X] Remove InputMap.
- [X] Decide where it makes sense to use size_t instead of uint32_t. Also VK_DEVICE_SIZE etc.
      Solution: use size_t for user-provided counts (i.e. number of color targets).
      Otherwise stick to types that correspond to underlying Vulkan structs.
- [X] With GLFW swapchain gets recreated immediately after launch.
- [ ] Replace VMA with custom allocator.
- [ ] Own implementation of Windows/Linux platform layers.
- [ ] Macro-based stuff should probably be internal.
      The goal is clean and minimal API that's 99% accessible from other languages.
