add_subdirectory(Triangle)
add_subdirectory(GLTFCube)
add_subdirectory(QuadTree)
add_subdirectory(SmoothGrid)
add_subdirectory(PrerenderedDepth)
add_subdirectory(Skybox)
add_subdirectory(BitonicSort)
add_subdirectory(PrefixSum)
add_subdirectory(GS)
add_subdirectory(BrushFade)
add_subdirectory(TransferThread)
add_subdirectory(LayeredImage)
add_subdirectory(Blur)
add_subdirectory(PBRRendering)
add_subdirectory(UIDemo)
add_subdirectory(Readback)
add_subdirectory(FixedTimestep)
add_subdirectory(BindingTest)
add_subdirectory(AllocatorTest)
